apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-service
  name: auth-service
  namespace: default
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    io.kompose.service: auth-service
status:
  loadBalancer: {}
