version: "3.9"
services:

  nginx:
    image: nginx
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - auth-service
      - user-service
    networks:
      - shopease-service

  auth-service:
    container_name: "auth_service"
    build: 
      context: ../
      dockerfile: ./deployments/auth/Dockerfile
    expose:
      - "8082"
      - "8085"
    depends_on:
      redis-auth:
        condition: service_healthy
    networks:
      - shopease-service
      - redis-auth-network

  user-service:
    container_name: "user_service"
    build: 
      context: ../
      dockerfile: ./deployments/user/Dockerfile
    expose:
      - "8080"
      - "8081"
    depends_on:
      postgres-user:
        condition: service_healthy
    networks:
      - postgres-user-network
      - shopease-service

  postgres-user:
    container_name: "postgres_user"
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "shopease"
      POSTGRES_PASSWORD: "uniq123"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U shopease -d user"]
        interval: 4s
        timeout: 3s
        retries: 5
    volumes:
      - ./user/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-user-network

  redis-auth:
    container_name: "redis_auth"
    image: redis
    expose:
      - "6379"
    environment:
      POSTGRES_DB: "post"
      POSTGRES_USER: "shopease"
      POSTGRES_PASSWORD: "uniq123"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 4s
      timeout: 3s
      retries: 5
    networks:
      - redis-auth-network


networks:
  shopease-service:
    name: shopease-service
    driver: bridge  
  postgres-user-network:
    name: postgres-user-network
    driver: bridge
  postgres-post-network:
    name: postgres-post-network
    driver: bridge
  redis-auth-network:
    name: redis-auth-network
    driver: bridge