apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-user
  name: postgres-user
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.31.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/postgres-user-network: "true"
        io.kompose.service: postgres-user
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: user
            - name: POSTGRES_PASSWORD
              value: uniq123
            - name: POSTGRES_USER
              value: shopease
          image: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready -U shopease -d user
            failureThreshold: 5
            periodSeconds: 4
            timeoutSeconds: 3
          name: postgres-user
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: postgres-user-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-user-claim0
          persistentVolumeClaim:
            claimName: postgres-user-claim0
status: {}
