apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-auth
  name: redis-auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.31.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/redis-auth-network: "true"
        io.kompose.service: redis-auth
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: post
            - name: POSTGRES_PASSWORD
              value: uniq123
            - name: POSTGRES_USER
              value: shopease
          image: redis
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --raw
                - incr
                - ping
            failureThreshold: 5
            periodSeconds: 4
            timeoutSeconds: 3
          name: redis-auth
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
